environment_config:
  path: environment_config.dart # optional, result file path against `lib/` folder
  dotenv_path: .env # optional, result file path for .env file against project root folder
  class: EnvironmentConfig # optional, class name
  
  fields: # set of fields for command
    version: # key name
      const: true # optional, default to TRUE
      default: 1.5.0beta4 # optional, default value for key, if not provided key will be required during command run
      dotenv: true # optional, default to FALSE, if this field should be added to .env file
   